### PR TITLE
Make pyofahrt creatable again

### PR DESCRIPTION
**Pull request by Miterion**
By deleting every migration and creating it from scratch

### CODE REVIEW

**Comment by exploide** [comment]
Any plan for updating the production instance once this gets merged?

**Comment by Miterion** [comment]
It has to be tested with the current production database before it gets deployed. 

On October 9, 2016 3:16:08 PM GMT+02:00, "Jannik V." <notifications@github.com> wrote:
>Any plan for updating the production instance once this gets merged?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/d120/pyofahrt/pull/36#issuecomment-252485858

-- 
Sent from my Android device.

**Comment by chriswars** [comment]
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0002_auto_20160429_1234, 0002_auto_20161009_1435 in workshops).
To fix them run 'python manage.py makemigrations --merge'


Mit dem gegebenen Command klappt es dann.  Sinnvoll so @exploide ?

**Comment by exploide** [comment]
Tested with production database. Could work this way. If you want to merge this PR, please execute `python manage.py makemigrations --merge` afterwards, commit the newly created migration and check if it works locally.

**Comment by chriswars** [comment]
Mit bestehender Datenbank gibt es war keine Probleme, jedoch funktioniert ein Neuaufsetzen immer noch nicht @Miterion

**Pull request merged**
